-- ============================================================
-- YeuHoc — Supabase Migration: Classroom & Teacher Role
-- Safe to re-run (idempotent). Run in Supabase SQL Editor.
-- Teacher role: run 20260612_add_teacher_role.sql first if needed.
-- ============================================================

-- ─── 1. Types ───────────────────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'classroom_member_status' AND n.nspname = 'public'
  ) THEN
    CREATE TYPE public.classroom_member_status AS ENUM ('pending', 'approved', 'rejected');
  END IF;
END $$;

-- ─── 2. Tables ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.classrooms (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  teacher_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  join_code TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.classroom_members (
  classroom_id UUID NOT NULL REFERENCES public.classrooms(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  status public.classroom_member_status NOT NULL DEFAULT 'pending',
  joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (classroom_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.classroom_exams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id UUID NOT NULL REFERENCES public.classrooms(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  subject TEXT,
  description TEXT,
  questions JSONB DEFAULT '[]'::jsonb,
  time_limit INTEGER,
  scoring_config JSONB,
  is_published BOOLEAN DEFAULT false,
  created_by UUID NOT NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.classroom_exam_results (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  classroom_id UUID NOT NULL REFERENCES public.classrooms(id) ON DELETE CASCADE,
  exam_id BIGINT NOT NULL REFERENCES public.classroom_exams(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  score NUMERIC(5,2),
  total_questions INTEGER,
  correct_answers INTEGER,
  wrong_answers INTEGER,
  unanswered INTEGER,
  answers JSONB DEFAULT '{}'::jsonb,
  question_time_spent JSONB DEFAULT '{}'::jsonb,
  time_spent INTEGER,
  violation_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.classroom_notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  classroom_id UUID NOT NULL REFERENCES public.classrooms(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  content TEXT,
  created_by UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ─── 3. Indexes ───────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_classrooms_teacher ON public.classrooms(teacher_id);
CREATE INDEX IF NOT EXISTS idx_classrooms_join_code ON public.classrooms(join_code);
CREATE INDEX IF NOT EXISTS idx_classroom_members_status ON public.classroom_members(status);
CREATE INDEX IF NOT EXISTS idx_classroom_members_user ON public.classroom_members(user_id);
CREATE INDEX IF NOT EXISTS idx_classroom_exams_classroom ON public.classroom_exams(classroom_id);
CREATE INDEX IF NOT EXISTS idx_classroom_results_user ON public.classroom_exam_results(user_id);
CREATE INDEX IF NOT EXISTS idx_classroom_results_exam ON public.classroom_exam_results(exam_id);
CREATE INDEX IF NOT EXISTS idx_classroom_notif_classroom ON public.classroom_notifications(classroom_id);

-- ─── 4. Triggers ──────────────────────────────────────────────
DROP TRIGGER IF EXISTS classrooms_updated_at ON public.classrooms;
CREATE TRIGGER classrooms_updated_at
  BEFORE UPDATE ON public.classrooms
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

DROP TRIGGER IF EXISTS classroom_exams_updated_at ON public.classroom_exams;
CREATE TRIGGER classroom_exams_updated_at
  BEFORE UPDATE ON public.classroom_exams
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- ─── 5. Storage bucket ────────────────────────────────────────
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'classroom-images',
  'classroom-images',
  true,
  5242880,
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/svg+xml']
) ON CONFLICT (id) DO NOTHING;

-- ─── 6. RLS ───────────────────────────────────────────────────
ALTER TABLE public.classrooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classroom_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classroom_exams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classroom_exam_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classroom_notifications ENABLE ROW LEVEL SECURITY;

-- Storage policies
DROP POLICY IF EXISTS "Classroom Images Public Access" ON storage.objects;
CREATE POLICY "Classroom Images Public Access"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'classroom-images');

DROP POLICY IF EXISTS "Classroom Images Teacher Upload" ON storage.objects;
CREATE POLICY "Classroom Images Teacher Upload"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'classroom-images' AND
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND (role::text = 'teacher' OR role::text = 'admin')
    )
  );

DROP POLICY IF EXISTS "Classroom Images Teacher Delete" ON storage.objects;
CREATE POLICY "Classroom Images Teacher Delete"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'classroom-images' AND
    (auth.uid() = owner OR EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role::text = 'admin'))
  );

-- Classrooms
DROP POLICY IF EXISTS "Anyone can view classrooms" ON public.classrooms;
CREATE POLICY "Anyone can view classrooms"
  ON public.classrooms FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Teachers can manage own classrooms" ON public.classrooms;
CREATE POLICY "Teachers can manage own classrooms"
  ON public.classrooms FOR ALL
  TO authenticated
  USING (
    auth.uid() = teacher_id AND
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND (role::text = 'teacher' OR role::text = 'admin'))
  )
  WITH CHECK (
    auth.uid() = teacher_id AND
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND (role::text = 'teacher' OR role::text = 'admin'))
  );

-- Classroom members
DROP POLICY IF EXISTS "Users can view members of their classrooms" ON public.classroom_members;
CREATE POLICY "Users can view members of their classrooms"
  ON public.classroom_members FOR SELECT
  TO authenticated
  USING (
    user_id = auth.uid() OR
    EXISTS (SELECT 1 FROM public.classrooms WHERE id = classroom_id AND teacher_id = auth.uid()) OR
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role::text = 'admin')
  );

DROP POLICY IF EXISTS "Users can request to join classroom" ON public.classroom_members;
CREATE POLICY "Users can request to join classroom"
  ON public.classroom_members FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "Teachers can manage class members" ON public.classroom_members;
CREATE POLICY "Teachers can manage class members"
  ON public.classroom_members FOR ALL
  TO authenticated
  USING (EXISTS (SELECT 1 FROM public.classrooms WHERE id = classroom_id AND teacher_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.classrooms WHERE id = classroom_id AND teacher_id = auth.uid()));

-- Classroom exams
DROP POLICY IF EXISTS "Members can view published exams" ON public.classroom_exams;
CREATE POLICY "Members can view published exams"
  ON public.classroom_exams FOR SELECT
  TO authenticated
  USING (
    (is_published = true AND EXISTS (
      SELECT 1 FROM public.classroom_members
      WHERE classroom_id = public.classroom_exams.classroom_id
        AND user_id = auth.uid()
        AND status = 'approved'
    ))
    OR EXISTS (SELECT 1 FROM public.classrooms WHERE id = classroom_id AND teacher_id = auth.uid())
    OR EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role::text = 'admin')
  );

DROP POLICY IF EXISTS "Teachers can manage exams" ON public.classroom_exams;
CREATE POLICY "Teachers can manage exams"
  ON public.classroom_exams FOR ALL
  TO authenticated
  USING (EXISTS (SELECT 1 FROM public.classrooms WHERE id = classroom_id AND teacher_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.classrooms WHERE id = classroom_id AND teacher_id = auth.uid()));

-- Classroom exam results
DROP POLICY IF EXISTS "Users view own results, teachers view all" ON public.classroom_exam_results;
CREATE POLICY "Users view own results, teachers view all"
  ON public.classroom_exam_results FOR SELECT
  TO authenticated
  USING (
    user_id = auth.uid() OR
    EXISTS (SELECT 1 FROM public.classrooms WHERE id = classroom_id AND teacher_id = auth.uid()) OR
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role::text = 'admin')
  );

DROP POLICY IF EXISTS "Users can insert own results" ON public.classroom_exam_results;
CREATE POLICY "Users can insert own results"
  ON public.classroom_exam_results FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "Teachers can delete results" ON public.classroom_exam_results;
CREATE POLICY "Teachers can delete results"
  ON public.classroom_exam_results FOR DELETE
  TO authenticated
  USING (
    EXISTS (SELECT 1 FROM public.classrooms WHERE id = classroom_id AND teacher_id = auth.uid())
    OR EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role::text = 'admin')
  );

-- Classroom notifications
DROP POLICY IF EXISTS "Members and teachers can view notifications" ON public.classroom_notifications;
CREATE POLICY "Members and teachers can view notifications"
  ON public.classroom_notifications FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.classroom_members
      WHERE classroom_id = public.classroom_notifications.classroom_id
        AND user_id = auth.uid()
        AND status = 'approved'
    )
    OR EXISTS (SELECT 1 FROM public.classrooms WHERE id = classroom_id AND teacher_id = auth.uid())
    OR EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role::text = 'admin')
  );

DROP POLICY IF EXISTS "Teachers can manage notifications" ON public.classroom_notifications;
CREATE POLICY "Teachers can manage notifications"
  ON public.classroom_notifications FOR ALL
  TO authenticated
  USING (EXISTS (SELECT 1 FROM public.classrooms WHERE id = classroom_id AND teacher_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.classrooms WHERE id = classroom_id AND teacher_id = auth.uid()));
